# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build an deploy
    runs-on: ubuntu-latest
    env:
      OWNER: windnow
      IMAGE: lkserver
    steps:
    - uses: actions/checkout@v4
    
#    - run: docker build -t ghcr.io/$OWNER/$IMAGE:latest .
#    
#    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin
#
#    - run: docker push ghcr.io/$OWNER/$IMAGE:latest
